### ISSUE TITLE
Would be nice to color points using 2D kernel density

### ISSUE THREAD

**Issue by DarwinAwardWinner** [LKremer/ggpointdensity#3]
Rather than counting nearest neighbors, it might be nice to be able to color each point based on the interpolated value of the 2D kernel density estimate at that point's location. You can do this using [`fields::interp.surface`](https://www.rdocumentation.org/packages/fields/versions/9.8-6/topics/interp.surface).

**Comment by DarwinAwardWinner** [comment]
This also potentially helps with #2, since I'm pretty sure 2D KDE's runtime isn't quadratic in the number of input points.

**Comment by LKremer** [comment]
I added `method="kde2d"`to the geom and stat. It is indeed faster for many points (~ >20k) but slower for few points.
