### ISSUE TITLE
adjust parameter not working in stat_pointdensity()

### ISSUE THREAD

**Issue by frederikziebell** [LKremer/ggpointdensity#6]
Independent of the value of 'adjust', I always get the same result. From the code, it seems the default 'adjust=1' is passed to the downstream StatPointDensity method.

**Comment by LKremer** [comment]
Hi Frederik,
Good catch! The adjust parameter indeed only worked when using the geom, but not in when using the stat. You're right, I passed `1` to StatPointDensity when I should've passed `adjust` instead.

I put the wrong number in the commit message, but [this commit](https://github.com/LKremer/ggpointdensity/commit/4960eca7ee2749311aa86475d05807e60750c44f) should fix the issue (please re-open issue if not).

Thanks for reporting this,
Lukas
