### ISSUE TITLE
Add this package to ggplot2-exts

### ISSUE THREAD

**Issue by Bisaloo** [LKremer/ggpointdensity#7]
https://www.ggplot2-exts.org/gallery/

It's super useful for users to help them discover your package:

https://github.com/ggplot2-exts/gallery#adding-a-ggplot2-extension

**Comment by LKremer** [comment]
This is a great suggestion! I'll do it when I find the time.

**Comment by LKremer** [comment]
Done. Thanks for the suggestion.
